Neos:
  Neos:
    Ui:
      frontendConfiguration:
        Carbon.CodePen:
          afx:
            fusionObjects:
              Fontawesome:
                documentation: Add icon from [Fontawesome 7 Free](https://fontawesome.com/search)
                snippet: <Carbon.Fontawesome:Icon icon="${1|solid,regular,brands|}:${2}" />
